# image: registry.gitlab.com/harkishen-singh/sel-tool-test
# image: node:latest
image: harkishen/selenium-ci-aossie-mtw-v1-test:latest

stages:
    # - installing_browsers
    - npms
    # - tests
    
# installing_browsers:
#     stage: installing_browsers
#     script:
#         - cat /etc/os-release
#         - set -xe
#         - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#         - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
#         - apt-get update -yqqq
#         - apt-get install -y google-chrome-stable

        
npms:
    stage: npms
    script:
        - cat /etc/os-release
        # - set -xe
        # - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        # - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
        # - apt-get update -yqqq
        # - apt-get install -y google-chrome-stable
        # # firefox
        # - wget --no-verbose -O /tmp/firefox.tar.bz2 https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0/linux-x86_64/en-US/firefox-57.0.tar.bz2
        # - tar -C /opt -xjf /tmp/firefox.tar.bz2 && mv /opt/firefox /opt/firefox-57.0 && ln -fs /opt/firefox-57.0/firefox /usr/bin/firefox
        # test environments 12 march 2019
        # Install Chrome browser
        # - set -xe
        # - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        # - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
        # Update packages
        # - apt-get update -yqqq
        - apt-get install -y xvfb
        # - apt-get install -y google-chrome-stable

        
        # Install Virtual Display emulator
        - npm install -g mocha
        - npm cache clear
        - npm install
        - echo "keys"
        - echo $yandex_translation_key
        - echo $yandex_dictionary_key
        - cd tests/
        -  xvfb-run -s "-screen 0 1920x1080x16" -a mocha app.js 
    cache:
        paths:
            - node_modules/